"""
Version: 1.0 (26 February, 2023)
Programmed by Mohammad Zunaed
"""

import torch

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
DATASET_ROOT_DIR = './datasets/'
MINI_IMAGENET_ROOT_DIR = './datasets/mini_imagenet_train/'

implemented_methods_list = ['baseline', 'proposed_md_DA',  'proposed_sd_DA']

all_configs = {
    # generate md results
    'baseline_md_chexpert_mimic':{
        'weight_saving_path': './weights/baseline_md_chexpert_mimic/',
        'checkpoint_root_path': None,
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': False,
        'epochs': 10,
        'style_source': 'natural',
        },
    'baseline_md_chexpert_mimic_mask_crop':{
        'weight_saving_path': './weights/baseline_md_chexpert_mimic_mask_crop/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'baseline_md_chexpert_mimic_mask_crop_il_srm':{
        'weight_saving_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_md_DA_chexpert_mimic':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    # ablation study
    'proposed_md_DA_chexpert_mimic_ablation1':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_ablation1/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': False,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_md_DA_chexpert_mimic_ablation2':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_ablation2/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': False,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': False,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_md_DA_chexpert_mimic_ablation3':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_ablation3/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': False, 
        'apply_gfe_loss': False,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    # image size 384, 512
    'proposed_md_DA_chexpert_mimic_384':{ # change image size and batch size to 384 and 90
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_384/',
        'checkpoint_root_path': './weights/proposed_md_DA_chexpert_mimic/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    # fl srm level-1,3
    'proposed_md_DA_chexpert_mimic_lvl1':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_lvl1/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 1,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_md_DA_chexpert_mimic_lvl3':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_lvl3/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 3,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    # style_source
    'baseline_md_chexpert_mimic_mask_crop_il_srm_cxr_source':{
        'weight_saving_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm_cxr_source/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'cxr',
        },
    'proposed_md_DA_chexpert_mimic_cxr_source':{
        'weight_saving_path': './weights/proposed_md_DA_chexpert_mimic_cxr_source/',
        'checkpoint_root_path': './weights/baseline_md_chexpert_mimic_mask_crop_il_srm_cxr_source/',
        'method': 'proposed_md_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'cxr',
        },
    
    # SD-cheXpert
    'baseline_sd_chexpert':{
        'weight_saving_path': './weights/baseline_sd_chexpert/',
        'checkpoint_root_path': None,
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': False,
        'epochs': 10,
        'style_source': 'natural',
        },
    'baseline_sd_chexpert_mask_crop':{
        'weight_saving_path': './weights/baseline_sd_chexpert_mask_crop/',
        'checkpoint_root_path': './weights/baseline_sd_chexpert/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'baseline_sd_chexpert_mask_crop_il_srm':{
        'weight_saving_path': './weights/baseline_sd_chexpert_mask_crop_il_srm/',
        'checkpoint_root_path': './weights/baseline_sd_chexpert_mask_crop/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_sd_DA_chexpert':{
        'weight_saving_path': './weights/proposed_sd_DA_chexpert/',
        'checkpoint_root_path': './weights/baseline_sd_chexpert_mask_crop_il_srm/',
        'method': 'proposed_sd_DA',
        'split_dict_path': './datasets/split_and_test_dicts/chexpert_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    # SD-Mimic
    'baseline_sd_mimic':{
        'weight_saving_path': './weights/baseline_sd_mimic/',
        'checkpoint_root_path': None,
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/mimic_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': False,
        'epochs': 10,
        'style_source': 'natural',
        },
    'baseline_sd_mimic_mask_crop':{
        'weight_saving_path': './weights/baseline_sd_mimic_mask_crop/',
        'checkpoint_root_path': './weights/baseline_sd_mimic/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/mimic_split_info_dict.npy',
        'apply_il_srm': False,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'baseline_sd_mimic_mask_crop_il_srm':{
        'weight_saving_path': './weights/baseline_sd_mimic_mask_crop_il_srm/',
        'checkpoint_root_path': './weights/baseline_sd_mimic_mask_crop/',
        'method': 'baseline',
        'split_dict_path': './datasets/split_and_test_dicts/mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'epochs': 5,
        'style_source': 'natural',
        },
    'proposed_sd_DA_mimic':{
        'weight_saving_path': './weights/proposed_sd_DA_mimic/',
        'checkpoint_root_path': './weights/baseline_sd_mimic_mask_crop_il_srm/',
        'method': 'proposed_sd_DA',
        'split_dict_path': './datasets/split_and_test_dicts/mimic_split_info_dict.npy',
        'apply_il_srm': True,
        'apply_lung_mask_crop': True,
        'apply_fl_srm': True,
        'apply_l_ccr': True, 
        'apply_l_scr': True, 
        'apply_gfe_loss': True,
        'fl_srm_level': 2,
        'epochs': 5,
        'style_source': 'natural',
        },
    
    
    }
